
[deployment]
  watsonx_apikey = "PLACEHOLDER FOR YOUR APIKEY"
  watsonx_url= ""  # should follow the format: `https://{REGION}.ml.cloud.ibm.com`
  space_id = "PLACEHOLDER FOR YOUR SPACE ID"
  deployment_id = "PLACEHOLDER FOR YOUR DEPLOYMENT ID"

[ai_service]
  model_id = "mistralai/mistral-large"  # underlying model of WatsonxChat
